import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PlayerContextProvider from "@/contexts/PlayerContext";
import { Toaster } from "@/components/ui/toaster";
import CanvasContextProvider from "@/contexts/CanvasContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PlayerContextProvider>
          {children}
          <Toaster />
        </PlayerContextProvider>
      </body>
    </html>
  );
}
